### PR TITLE
feat: add model gpt-4

### PR DESCRIPTION
**Pull request by AeroXi**
I added gpt-4 model, for now, users need access to gpt-4 to use it.
image

### CODE REVIEW

**Comment by AeroXi** [comment]
This commit removes semicolons. I didn't do that, seems like it's your .prettierrc in this repo, which automatically removes the semicolons.

**Comment by anc95** [comment]
> This commit removes semicolons. I didn't do that, seems like it's your .prettierrc in this repo, which automatically removes the semicolons. 

Thank you. No worry for the prettier.

I just want to confirm have you tested the gpt-4 model works in your side. Cause I don't have the access to gpt-4 now, I can't perform test with this

**Comment by AeroXi** [comment]
Yes, I have tested it.
image

**Comment by AeroXi** [comment]
#13 finished

**Pull request merged**
